fix HPAs by setting resource requests
giantswarm/loki-app pull request #252
Opened 2023-12-04 19:48 UTC by hervenicol

Towards https://github.com/giantswarm/giantswarm/issues/29149

### Backend HPA:

Resources definition for the ruler were broken because the `sidecar` section was defined twice in default values.
Now both definitions are merged.

### Gateway HPA

Added resources request for dnsmasq sidecar

2023-12-04 20:03 UTC, hervenicol commented
Successfully tested on `gaia`.

2023-12-04 20:09 UTC, TheoBrigitte requested changes

2023-12-04 20:09 UTC, TheoBrigitte commented on CHANGELOG.md
> +- resources set for dnsmasq sidecar (fixes gateway HPA)
I would rather write something like:

```suggestion
- Fix requests/limits for sidecar container (fixes backend HPA)
- Add requests/limits for dnsmasq container (fixes gateway HPA)
```

2023-12-05 08:37 UTC, QuantumEnigmaa approved these changes

2023-12-11 15:19 UTC, TheoBrigitte approved these changes

2023-12-12 10:25 UTC, merged